openapi: 3.0.0
info:
  title: Coffee Shop API
  version: 1.0.0
  description: API schema for authentication via phone and OTP.
servers:
  - url: http://localhost:3000
paths:
  /api/hello:
    get:
      summary: Health hello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Error
  /api/status:
    get:
      summary: Health status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
        '500':
          description: Internal Error

  /api/auth/send-otp:
    post:
      summary: Send OTP to phone (demo returns code)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone]
              properties:
                phone:
                  type: string
                  description: Phone number, digits only are used
      responses:
        '200':
          description: OTP generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  demoCode:
                    type: string
                    description: Returned only in development
                  expiresAt:
                    type: string
                    format: date-time
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string

  /api/auth/verify-otp:
    post:
      summary: Verify OTP and issue JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, code]
              properties:
                phone:
                  type: string
                code:
                  type: string
      responses:
        '200':
          description: Authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Invalid input or code
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
        '429':
          description: Too many attempts
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string

  /api/auth/me:
    get:
      summary: Get current user by JWT
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: 'Bearer <token>'
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      message:
                        type: string

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        phone:
          type: string
        name:
          type: string
        bonuses:
          type: object
          properties:
            balance:
              type: number
            totalEarned:
              type: number
            totalRedeemed:
              type: number
        totalSpend:
          type: number
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
